### ISSUE TITLE
Not Showing 1 Location

### ISSUE THREAD

**Issue by stsjon** [clakeb/custom-business-locations#2]
I have 4 locations entered, and 3 of them work great. The 4th however I can not get to show up. I make sure I click on the selection link that pops below the address while typing, and it doesn't show up. 

Also when I do click on the location on the front end of the plugin, it expands and shows me the info, but the map just sits there.

**Comment by stsjon** [comment]
Link: http://goo.gl/xbwye

**Comment by stsjon** [comment]
Closing -- addressed with information of a new version coming.

**Comment by tatemz** [comment]
New version out. Would love it if you ran through it and reported what bugs you see.  Thanks for the download!
